(ns ethlance.components.language-select-field
  (:require [cljs-react-material-ui.reagent :as ui]))

(def languages
  [
   "аҧсуа бызшәа, аҧсшәа"
   "Afaraf"
   "Afrikaans"
   "Akan"
   "Shqip"
   "አማርኛ"
   "العربية"
   "aragonés"
   "Հայերեն"
   "অসমীয়া"
   "авар мацӀ, магӀарул мацӀ"
   "avesta"
   "aymar aru"
   "azərbaycan dili"
   "bamanankan"
   "башҡорт теле"
   "euskara, euskera"
   "беларуская мова"
   "বাংলা"
   "भोजपुरी"
   "Bislama"
   "bosanski jezik"
   "brezhoneg"
   "български език"
   "ဗမာစာ"
   "català"
   "Chamoru"
   "нохчийн мотт"
   "chiCheŵa, chinyanja"
   "中文 (Zhōngwén), 汉语, 漢語"
   "чӑваш чӗлхи"
   "Kernewek"
   "corsu, lingua corsa"
   "ᓀᐦᐃᔭᐍᐏᐣ"
   "hrvatski jezik"
   "čeština, český jazyk"
   "dansk"
   "Nederlands, Vlaams"
   "རྫོང་ཁ"
   "English"
   "Esperanto"
   "eesti, eesti keel"
   "Eʋegbe"
   "føroyskt"
   "vosa Vakaviti"
   "suomi, suomen kieli"
   "français, langue française"
   "Fulfulde, Pulaar, Pular"
   "galego"
   "ქართული"
   "Deutsch"
   "ελληνικά"
   "Avañe'ẽ"
   "ગુજરાતી"
   "Kreyòl ayisyen"
   "(Hausa) هَوُسَ"
   "עברית"
   "Otjiherero"
   "हिन्दी, हिंदी"
   "Hiri Motu"
   "magyar"
   "Interlingua"
   "Bahasa Indonesia"
   "Interlingue"
   "Gaeilge"
   "Asụsụ Igbo"
   "Iñupiaq, Iñupiatun"
   "Ido"
   "Íslenska"
   "italiano"
   "ᐃᓄᒃᑎᑐᑦ"
   "日本語 (にほんご)"
   "Basa Jawa"
   "kalaallisut, kalaallit oqaasii"
   "ಕನ್ನಡ"
   "Kanuri"
   "कश्मीरी, كشميري‎"
   "қазақ тілі"
   "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ"
   "Gĩkũyũ"
   "Ikinyarwanda"
   "Кыргызча, Кыргыз тили"
   "коми кыв"
   "Kikongo"
   "한국어"
   "Kurdî, كوردی‎"
   "Kuanyama"
   "latine, lingua latina"
   "Lëtzebuergesch"
   "Luganda"
   "Limburgs"
   "Lingála"
   "ພາສາລາວ"
   "lietuvių kalba"
   "Tshiluba"
   "latviešu valoda"
   "Gaelg, Gailck"
   "македонски јазик"
   "fiteny malagasy"
   "bahasa Melayu, بهاس ملايو‎"
   "മലയാളം"
   "Malti"
   "te reo Māori"
   "मराठी"
   "Kajin M̧ajeļ"
   "Монгол хэл"
   "Dorerin Naoero"
   "Diné bizaad"
   "isiNdebele"
   "नेपाली"
   "Owambo"
   "Norsk bokmål"
   "Norsk nynorsk"
   "Norsk"
   "ꆈꌠ꒿ Nuosuhxop"
   "isiNdebele"
   "occitan, lenga d'òc"
   "ᐊᓂᔑᓈᐯᒧᐎᓐ"
   "ѩзыкъ словѣньскъ"
   "Afaan Oromoo"
   "ଓଡ଼ିଆ"
   "ирон æвзаг"
   "ਪੰਜਾਬੀ"
   "पाऴि"
   "فارسی"
   "język polski, polszczyzna"
   "پښتو"
   "Português"
   "Runa Simi, Kichwa"
   "rumantsch grischun"
   "Ikirundi"
   "Română"
   "Русский"
   "संस्कृतम्"
   "sardu"
   "सिन्धी, سنڌي، سندھی‎"
   "Davvisámegiella"
   "gagana fa'a Samoa"
   "yângâ tî sängö"
   "српски језик"
   "Gàidhlig"
   "chiShona"
   "සිංහල"
   "slovenčina, slovenský jazyk"
   "slovenski jezik, slovenščina"
   "Soomaaliga, af Soomaali"
   "Sesotho"
   "español"
   "Basa Sunda"
   "Kiswahili"
   "SiSwati"
   "svenska"
   "தமிழ்"
   "తెలుగు"
   "тоҷикӣ, toçikī, تاجیکی‎"
   "ไทย"
   "ትግርኛ"
   "བོད་ཡིག"
   "Türkmen, Түркмен"
   "Wikang Tagalog"
   "Setswana"
   "faka Tonga"
   "Türkçe"
   "Xitsonga"
   "татар теле, tatar tele"
   "Twi"
   "Reo Tahiti"
   "ئۇيغۇرچە ‎Uyghurche"
   "Українська"
   "اردو"
   "Oʻzbek, Ўзбек, أۇزبېك‎"
   "Tshivenḓa"
   "Tiếng Việt"
   "Volapük"
   "walon"
   "Cymraeg"
   "Wollof"
   "Frysk"
   "isiXhosa"
   "ייִדיש"
   "Yorùbá"
   "Saɯ cueŋƅ, Saw cuengh"
   "isiZulu"
   ])

(defn language-select-field []
  (fn [{:keys [value] :as props}]
    [ui/auto-complete
     (merge
       {:floating-label-text "Language"
        :open-on-focus true
        :dataSource languages
        :filter (aget js/MaterialUI "AutoComplete" "caseInsensitiveFilter")
        :search-text (if (or (not value) (zero? value))
                       ""
                       (nth languages (dec value)))
        :list-style {:max-height 300}}
       props
       (when-let [on-new-request (:on-new-request props)]
         {:on-new-request (fn [value index]
                            (on-new-request value (inc index)))
          :on-update-input (fn [text]
                             (when-not (seq text)
                               (on-new-request "" 0)))}))]))
