language: clojure
script: lein test
notifications:
  email:
  recipients:
    - juan@district0x.io
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
before_install:
- sudo wget --no-check-certificate -P /bin https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux
- sudo chmod a+x /bin/solc-static-linux
- sudo ln -s /bin/solc-static-linux /usr/bin/solc
services:
  - docker
deploy:
- provider: script
  script: bash docker-push.sh prod
  on:
    branch: production
