version: "3.1"
services:
    db-postgresql:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ethlanceuser_new
            POSTGRES_PASSWORD: pass_new
            POSTGRES_DB: ethlance_new
    server:
        image: ethlance-server:latest
        container_name: ethlance-server
        build:
            context: .
            dockerfile: "docker-builds/server/Dockerfile"
            args:
                ETHLANCE_ENV: "dev"
        ports:
            - 6300:6300
        command: ["node", "ethlance_server.js"]
        environment:
            ETHLANCE_ENV: "dev"
        depends_on:
            - db-postgresql
    ui:
        image: ethlance-ui:latest
        container_name: ethlance-ui
        ports:
            - 9080:80
        build:
            context: .
            dockerfile: "docker-builds/ui/Dockerfile"
            args:
                ETHLANCE_ENV: "dev"
        depends_on:
            - server
        environment:
            ETHLANCE_ENV: "dev"

    #  Collect deps, compiles and deploys contracts
    base:
        image: ethlance-base:local
        container_name: ethlance-base
        command: ["exit", "0"]
        build:
            context: .
            dockerfile: "docker-builds/base/Dockerfile"
            args:
                ETHLANCE_ENV: "dev"
        environment:
            ETHLANCE_ENV: "dev"
