version: "3.1"
services:
    db-postgresql:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
    server:
        image: ${DOCKER_REGISTRY}/ethlance-server:latest
        container_name: ethlance-server
        build:
            context: .
            dockerfile: "docker-builds/server/Dockerfile"
            args:
                ETHLANCE_ENV: ${ETHLANCE_ENV}
                DOCKER_REGISTRY: ${DOCKER_REGISTRY}
                ETHLANCE_DEPLOY_SEED: ${ETHLANCE_DEPLOY_SEED}
        ports:
            - 6300:6300
        command: ["node", "ethlance_server.js"]
        environment:
            ETHLANCE_ENV: ${ETHLANCE_ENV}
    ui:
        image: ${DOCKER_REGISTRY}/ethlance-ui:latest
        container_name: ethlance-ui
        ports:
            - 9080:80
        build:
            context: .
            dockerfile: "docker-builds/ui/Dockerfile"
            args:
                ETHLANCE_ENV: ${ETHLANCE_ENV}
                DOCKER_REGISTRY: ${DOCKER_REGISTRY}
                ETHLANCE_DEPLOY_SEED: ${ETHLANCE_DEPLOY_SEED}
        depends_on:
            - server
        environment:
            ETHLANCE_ENV: ${ETHLANCE_ENV}