version: "3.1"
services:
    db-postgresql:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
    server:
        image: 487920318758.dkr.ecr.us-west-2.amazonaws.com/ethlance-server:latest-prod
        container_name: ethlance-server
        build:
            context: .
            dockerfile: "docker-builds/server/Dockerfile"
            args:
                ETHLANCE_ENV: "prod"
        ports:
            - 6300:6300
        command: ["node", "ethlance_server.js"]
        environment:
            ETHLANCE_ENV: "prod"
    ui:
        image: 487920318758.dkr.ecr.us-west-2.amazonaws.com/ethlance-ui:latest-prod
        container_name: ethlance-ui
        ports:
            - 9080:80
        build:
            context: .
            dockerfile: "docker-builds/ui/Dockerfile"
            args:
                ETHLANCE_ENV: "prod"
        depends_on:
            - server
        environment:
            ETHLANCE_ENV: "prod"

    #  Collect deps, compiles and deploys contracts
    base:
        image: ethlance-base:local
        container_name: ethlance-base
        command: ["exit", "0"]
        build:
            context: .
            dockerfile: "docker-builds/base/Dockerfile"
            args:
                ETHLANCE_ENV: "prod"
        environment:
            ETHLANCE_ENV: "prod"
