#+TITLE: Ethlance Tasks
#+AUTHOR: Benjamin Zaporzan
#+DATE: 2019-01-04
#+EMAIL: benzaporzan@gmail.com
#+LANGUAGE: en
#+OPTIONS: H:2 num:t toc:t \n:nil ::t |:t ^:t f:t tex:t
* Tasks
** General
*** TODO Ensure production build works correctly
    ie. ~make build~
    - Should work with district.config and include production defaults
*** TODO Look into creating a Docker image from the production build.
*** TODO Develop Spec from new Design Work
** Server
*** TODO Redevelop (ON HOLD)
    - Need more info on private blockchain and how it ties into the
      original design, focusing on UI.
** UI
*** Components
    Ethlance pages consist of 'components', which reside in the
    src/../ethlance/ui/component folder with related styling stored
    in resources/less/component folder

**** Ethlance Input Select [1/3]
     Selection dropdown with multi selections. Choosing one selection
     from a dropdown listing.

     - [X] Draft Implementation
     - [ ] Introduce more styling
     - [ ] Include optional search bar. When text is entered, the
       dropdown listing only contains values that include the text entered.

**** Ethlance Input Text [0/1]
     Generalized input text field for entering information ie. <input type='text'>

     - [ ] Feature: Continue to show label while focused. Use similar
       transitions compared to material UI

**** Ethlance Input Currency [0/1]
     Similar in nature to the text input, except it only accepts
     currency values. Only numbers should be allowed within the field.

     - [ ] Draft Implementation

**** Ethlance Owl View [0/1]
     Used on the splash page as a carousel. Example can be seen in the
     ethlance design site.

     - [ ] Draft Implementation

**** Ethlance Chip Search Input [0/1]
     Allows you to search through auto-suggested fields, with 'chips'
     being produced when you choose certain chip values.

     - [ ] Draft Implementation

*** Pages
**** Splash Page [/]
     Several SVG animations that need to be correctly handled on the
     splash page, which should be able to make use of inline-svg with
     css styling animations.

     - [ ] SVG Animations

**** Jobs [/]

**** Sign Up [/]

     

*** TODO UI-Only Compilation
    - ON HOLD until rework is placed on a public testnet.
** Smart Contracts
*** TODO Redevelop Spec from new Design
