(ns ethlance.shared.constants)

(def countries
  ["United States"
   "Afghanistan"
   "Albania"
   "Algeria"
   "Andorra"
   "Angola"
   "Antigua & Deps"
   "Argentina"
   "Armenia"
   "Australia"
   "Austria"
   "Azerbaijan"
   "Bahamas"
   "Bahrain"
   "Bangladesh"
   "Barbados"
   "Belarus"
   "Belgium"
   "Belize"
   "Benin"
   "Bhutan"
   "Bolivia"
   "Bosnia Herzegovina"
   "Botswana"
   "Brazil"
   "Brunei"
   "Bulgaria"
   "Burkina"
   "Burundi"
   "Cambodia"
   "Cameroon"
   "Canada"
   "Cape Verde"
   "Central African Rep"
   "Chad"
   "Chile"
   "China"
   "Colombia"
   "Comoros"
   "Congo"
   "Congo {Democratic Rep}"
   "Costa Rica"
   "Croatia"
   "Cuba"
   "Cyprus"
   "Czech Republic"
   "Denmark"
   "Djibouti"
   "Dominica"
   "Dominican Republic"
   "East Timor"
   "Ecuador"
   "Egypt"
   "El Salvador"
   "Equatorial Guinea"
   "Eritrea"
   "Estonia"
   "Ethiopia"
   "Fiji"
   "Finland"
   "France"
   "Gabon"
   "Gambia"
   "Georgia"
   "Germany"
   "Ghana"
   "Greece"
   "Grenada"
   "Guatemala"
   "Guinea"
   "Guinea-Bissau"
   "Guyana"
   "Haiti"
   "Honduras"
   "Hungary"
   "Iceland"
   "India"
   "Indonesia"
   "Iran"
   "Iraq"
   "Ireland {Republic}"
   "Israel"
   "Italy"
   "Ivory Coast"
   "Jamaica"
   "Japan"
   "Jordan"
   "Kazakhstan"
   "Kenya"
   "Kiribati"
   "Korea North"
   "Korea South"
   "Kosovo"
   "Kuwait"
   "Kyrgyzstan"
   "Laos"
   "Latvia"
   "Lebanon"
   "Lesotho"
   "Liberia"
   "Libya"
   "Liechtenstein"
   "Lithuania"
   "Luxembourg"
   "Macedonia"
   "Madagascar"
   "Malawi"
   "Malaysia"
   "Maldives"
   "Mali"
   "Malta"
   "Marshall Islands"
   "Mauritania"
   "Mauritius"
   "Mexico"
   "Micronesia"
   "Moldova"
   "Monaco"
   "Mongolia"
   "Montenegro"
   "Morocco"
   "Mozambique"
   "Myanmar, {Burma}"
   "Namibia"
   "Nauru"
   "Nepal"
   "Netherlands"
   "New Zealand"
   "Nicaragua"
   "Niger"
   "Nigeria"
   "Norway"
   "Oman"
   "Pakistan"
   "Palau"
   "Panama"
   "Papua New Guinea"
   "Paraguay"
   "Peru"
   "Philippines"
   "Poland"
   "Portugal"
   "Qatar"
   "Romania"
   "Russian Federation"
   "Rwanda"
   "St Kitts & Nevis"
   "St Lucia"
   "Saint Vincent & the Grenadines"
   "Samoa"
   "San Marino"
   "Sao Tome & Principe"
   "Saudi Arabia"
   "Senegal"
   "Serbia"
   "Seychelles"
   "Sierra Leone"
   "Singapore"
   "Slovakia"
   "Slovenia"
   "Solomon Islands"
   "Somalia"
   "South Africa"
   "South Sudan"
   "Spain"
   "Sri Lanka"
   "Sudan"
   "Suriname"
   "Swaziland"
   "Sweden"
   "Switzerland"
   "Syria"
   "Taiwan"
   "Tajikistan"
   "Tanzania"
   "Thailand"
   "Togo"
   "Tonga"
   "Trinidad & Tobago"
   "Tunisia"
   "Turkey"
   "Turkmenistan"
   "Tuvalu"
   "Uganda"
   "Ukraine"
   "United Arab Emirates"
   "United Kingdom"
   "Uruguay"
   "Uzbekistan"
   "Vanuatu"
   "Vatican City"
   "Venezuela"
   "Vietnam"
   "Yemen"
   "Zambia"
   "Zimbabwe"])

(def languages
  ["аҧсуа бызшәа, аҧсшәа"
   "Afaraf"
   "Afrikaans"
   "Akan"
   "Shqip"
   "አማርኛ"
   "العربية"
   "aragonés"
   "Հայերեն"
   "অসমীয়া"
   "авар мацӀ, магӀарул мацӀ"
   "avesta"
   "aymar aru"
   "azərbaycan dili"
   "bamanankan"
   "башҡорт теле"
   "euskara, euskera"
   "беларуская мова"
   "বাংলা"
   "भोजपुरी"
   "Bislama"
   "bosanski jezik"
   "brezhoneg"
   "български език"
   "ဗမာစာ"
   "català"
   "Chamoru"
   "нохчийн мотт"
   "chiCheŵa, chinyanja"
   "中文 (Zhōngwén), 汉语, 漢語"
   "чӑваш чӗлхи"
   "Kernewek"
   "corsu, lingua corsa"
   "ᓀᐦᐃᔭᐍᐏᐣ"
   "hrvatski jezik"
   "čeština, český jazyk"
   "dansk"
   "Nederlands, Vlaams"
   "རྫོང་ཁ"
   "English"
   "Esperanto"
   "eesti, eesti keel"
   "Eʋegbe"
   "føroyskt"
   "vosa Vakaviti"
   "suomi, suomen kieli"
   "français, langue française"
   "Fulfulde, Pulaar, Pular"
   "galego"
   "ქართული"
   "Deutsch"
   "ελληνικά"
   "Avañe'ẽ"
   "ગુજરાતી"
   "Kreyòl ayisyen"
   "(Hausa) هَوُسَ"
   "עברית"
   "Otjiherero"
   "हिन्दी, हिंदी"
   "Hiri Motu"
   "magyar"
   "Interlingua"
   "Bahasa Indonesia"
   "Interlingue"
   "Gaeilge"
   "Asụsụ Igbo"
   "Iñupiaq, Iñupiatun"
   "Ido"
   "Íslenska"
   "italiano"
   "ᐃᓄᒃᑎᑐᑦ"
   "日本語 (にほんご)"
   "Basa Jawa"
   "kalaallisut, kalaallit oqaasii"
   "ಕನ್ನಡ"
   "Kanuri"
   "कश्मीरी, كشميري‎"
   "қазақ тілі"
   "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ"
   "Gĩkũyũ"
   "Ikinyarwanda"
   "Кыргызча, Кыргыз тили"
   "коми кыв"
   "Kikongo"
   "한국어"
   "Kurdî, كوردی‎"
   "Kuanyama"
   "latine, lingua latina"
   "Lëtzebuergesch"
   "Luganda"
   "Limburgs"
   "Lingála"
   "ພາສາລາວ"
   "lietuvių kalba"
   "Tshiluba"
   "latviešu valoda"
   "Gaelg, Gailck"
   "македонски јазик"
   "fiteny malagasy"
   "bahasa Melayu, بهاس ملايو‎"
   "മലയാളം"
   "Malti"
   "te reo Māori"
   "मराठी"
   "Kajin M̧ajeļ"
   "Монгол хэл"
   "Dorerin Naoero"
   "Diné bizaad"
   "नेपाली"
   "Owambo"
   "Norsk bokmål"
   "Norsk nynorsk"
   "Norsk"
   "ꆈꌠ꒿ Nuosuhxop"
   "isiNdebele"
   "occitan, lenga d'òc"
   "ᐊᓂᔑᓈᐯᒧᐎᓐ"
   "ѩзыкъ словѣньскъ"
   "Afaan Oromoo"
   "ଓଡ଼ିଆ"
   "ирон æвзаг"
   "ਪੰਜਾਬੀ"
   "पाऴि"
   "فارسی"
   "język polski, polszczyzna"
   "پښتو"
   "Português"
   "Runa Simi, Kichwa"
   "rumantsch grischun"
   "Ikirundi"
   "Română"
   "Русский"
   "संस्कृतम्"
   "sardu"
   "सिन्धी, سنڌي، سندھی‎"
   "Davvisámegiella"
   "gagana fa'a Samoa"
   "yângâ tî sängö"
   "српски језик"
   "Gàidhlig"
   "chiShona"
   "සිංහල"
   "slovenčina, slovenský jazyk"
   "slovenski jezik, slovenščina"
   "Soomaaliga, af Soomaali"
   "Sesotho"
   "español"
   "Basa Sunda"
   "Kiswahili"
   "SiSwati"
   "svenska"
   "தமிழ்"
   "తెలుగు"
   "тоҷикӣ, toçikī, تاجیکی‎"
   "ไทย"
   "ትግርኛ"
   "བོད་ཡིག"
   "Türkmen, Түркмен"
   "Wikang Tagalog"
   "Setswana"
   "faka Tonga"
   "Türkçe"
   "Xitsonga"
   "татар теле, tatar tele"
   "Twi"
   "Reo Tahiti"
   "ئۇيغۇرچە ‎Uyghurche"
   "Українська"
   "اردو"
   "Oʻzbek, Ўзбек, أۇزبېك‎"
   "Tshivenḓa"
   "Tiếng Việt"
   "Volapük"
   "walon"
   "Cymraeg"
   "Wollof"
   "Frysk"
   "isiXhosa"
   "ייִדיש"
   "Yorùbá"
   "Saɯ cueŋƅ, Saw cuengh"
   "isiZulu"])
   
