name: docker_build

on:
  push:
    branches:
      - add_dockerfiles
      # - main
      # - master

      
permissions:
  contents: read

jobs:
  docker_build:
    strategy:
      matrix:
        image: ["server", "ui"]
        env: ["qa"]
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: district0x/ethlance-config
          path: ethlance-config
          token: ${{ secrets.ETHLANCE_CONFIG_PAT }}
          ref: docker_build
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: list repo
        run: |
          echo "Checking repo contents"
          ls -lah 
          ls -lah ethlance-config/
          # ls -lah config/

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     file: docker-builds/${{ matrix.image }}/Dockerfile
      #     build-args: BUILD_ENV=${{ matrix.env }}
      #     push: true
      #     tags: ${{ secrets.ECR_REGISTRY }}/streamtide-${{ matrix.image }}:latest-${{ matrix.env }}
